module.exports = [
  {
    tableName: 'research_Papers',
    data: [
      {
        paper_id: null,
        paper_title: 'Intro to Mobile App Dev',
        conference: 'Mobile Tech Conf',
        publish_date: new Date('2022-01-01'),
        author_id: 7,
      },
      {
        paper_id: null,
        paper_title: 'UX Design for Mobile Apps',
        conference: 'HCI Conf',
        publish_date: new Date('2022-02-01'),
        author_id: 3,
      },
      {
        paper_id: null,
        paper_title: 'Security in App Development',
        conference: 'InfoSec Symposium',
        publish_date: new Date('2022-03-01'),
        author_id: 2,
      },
      {
        paper_id: null,
        paper_title: 'Cross-Platform App Dev Trends',
        conference: 'Mobile & Web Conf',
        publish_date: new Date('2022-04-01'),
        author_id: 8,
      },
      {
        paper_id: null,
        paper_title: 'App Monetization Strategies',
        conference: 'Mobile Business Conf',
        publish_date: new Date('2022-05-01'),
        author_id: 11,
      },
      {
        paper_id: null,
        paper_title: 'Cloud Computing for Mobile',
        conference: 'IEEE Cloud Conf',
        publish_date: new Date('2022-06-01'),
        author_id: 9,
      },
      {
        paper_id: null,
        paper_title: 'App Testing & QA',
        conference: 'Software Testing Conf',
        publish_date: new Date('2022-07-01'),
        author_id: 12,
      },
      {
        paper_id: null,
        paper_title: 'Agile Dev in Mobile Apps',
        conference: 'Agile Software Conf',
        publish_date: new Date('2022-08-01'),
        author_id: 13,
      },
      {
        paper_id: null,
        paper_title: 'Machine Learning in Apps',
        conference: 'AI Conf',
        publish_date: new Date('2022-09-01'),
        author_id: 6,
      },
      {
        paper_id: null,
        paper_title: 'Usability Testing for Apps',
        conference: 'HCI Conf',
        publish_date: new Date('2022-10-01'),
        author_id: 3,
      },
      {
        paper_id: null,
        paper_title: 'App Analytics & Metrics',
        conference: 'Data Analytics Conf',
        publish_date: new Date('2022-11-01'),
        author_id: 7,
      },
      {
        paper_id: null,
        paper_title: 'App Localization & Intl.',
        conference: 'Intl. & Unicode Conf',
        publish_date: new Date('2022-12-01'),
        author_id: 3,
      },
      {
        paper_id: null,
        paper_title: 'Gamification in App Dev',
        conference: 'Gamification Europe',
        publish_date: new Date('2023-01-01'),
        author_id: 8,
      },
      {
        paper_id: null,
        paper_title: 'Emerging Tech in App Dev',
        conference: 'Future Tech Conf',
        publish_date: new Date('2023-02-01'),
        author_id: 9,
      },
      {
        paper_id: null,
        paper_title: 'App Accessibility & Inclusive Design',
        conference: 'HCI Accessibility Conf',
        publish_date: new Date('2023-03-01'),
        author_id: 13,
      },
      {
        paper_id: null,
        paper_title: 'Impact of Apps on Society',
        conference: 'Social Implications Conf',
        publish_date: new Date('2023-04-01'),
        author_id: 15,
      },
      {
        paper_id: null,
        paper_title: 'Health & Fitness Apps',
        conference: 'Mobile Health Conf',
        publish_date: new Date('2023-05-01'),
        author_id: 8,
      },
      {
        paper_id: null,
        paper_title: 'AI in App Personalization',
        conference: 'Personalization Conf',
        publish_date: new Date('2023-06-01'),
        author_id: 1,
      },
      {
        paper_id: null,
        paper_title: 'Progressive Web Apps',
        conference: 'Web Engineering Conf',
        publish_date: new Date('2023-07-01'),
        author_id: 3,
      },
      {
        paper_id: null,
        paper_title: 'Ethical Considerations in App Dev',
        conference: 'Ethics & Tech Conf',
        publish_date: new Date('2023-08-01'),
        author_id: 9,
      },
      {
        paper_id: null,
        paper_title: 'App Gamification',
        conference: 'Business Gamification Conf',
        publish_date: new Date('2023-09-01'),
        author_id: 10,
      },
      {
        paper_id: null,
        paper_title: 'Blockchain for App Transactions',
        conference: 'Blockchain Tech Conf',
        publish_date: new Date('2023-10-01'),
        author_id: 6,
      },
      {
        paper_id: null,
        paper_title: 'App Dev for Education',
        conference: 'EdTech Conf',
        publish_date: new Date('2023-11-01'),
        author_id: 5,
      },
      {
        paper_id: null,
        paper_title: 'Chatbot Integration in Apps',
        conference: 'Conversational Agents Conf',
        publish_date: new Date('2023-12-01'),
        author_id: 10,
      },
      {
        paper_id: null,
        paper_title: 'App Performance Optimization',
        conference: 'Performance Engineering Conf',
        publish_date: new Date('2024-01-01'),
        author_id: 5,
      },
      {
        paper_id: null,
        paper_title: 'App User Engagement Strategies',
        conference: 'User Experience Conf',
        publish_date: new Date('2024-02-01'),
        author_id: 4,
      },
      {
        paper_id: null,
        paper_title: 'AR Integration in Mobile Apps',
        conference: 'Mixed & Augmented Reality Conf',
        publish_date: new Date('2024-03-01'),
        author_id: 11,
      },
      {
        paper_id: null,
        paper_title: 'App Accessibility for Disabilities',
        conference: 'Computers Helping People Conf',
        publish_date: new Date('2024-04-01'),
        author_id: 13,
      },
      {
        paper_id: null,
        paper_title: 'IoT Integration in Apps',
        conference: 'Internet of Things Conf',
        publish_date: new Date('2024-05-01'),
        author_id: 3,
      },
      {
        paper_id: null,
        paper_title: 'App Localization for Global Markets',
        conference: 'Intl. & Unicode Conf',
        publish_date: new Date('2024-06-01'),
        author_id: 7,
      },
    ],
  },
];
